In [7]:
pip install xgboost


   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 330.3 kB/s eta 0:06:19
   ---------------------------------------- 0.1/124.9 MB 655.4 kB/s eta 0:03:11
   ---------------------------------------- 0.2/124.9 MB 1.4 MB/s eta 0:01:31
   ---------------------------------------- 0.3/124.9 MB 1.4 MB/s eta 0:01:32
   ---------------------------------------- 0.7/124.9 MB 2.6 MB/s eta 0:00:48
   ---------------------------------------- 0.8/124.9 MB 2.8 MB/s eta 0:00:45
   ---------------------------------------- 1.1/124.9 MB 2.9 MB/s eta 0:00:43
   ---------------------------------------- 1.3/124.9 MB 3.2 MB/s eta 0:00:39
   ---------------------------------------- 1.5/124.9 MB 3.3 MB/s eta 0:00:38
    --------------------------------------- 1.6/124.9 MB 3.3 MB/s eta 0:00:37
    --------------------------------------- 1.9/124.9 MB 3.5 MB/s eta 0:0

In [12]:
import numpy as np
import xgboost as xgb
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split , KFold , StratifiedKFold, cross_val_score
import warnings
warnings.filterwarnings('ignore')

In [26]:
x , y = make_classification (n_samples = 1000 , n_features = 20 , n_informative = 2 , n_redundant=10, random_state=42)
x_train , x_test , y_train , y_test =train_test_split(x , y , test_size = 0.30 , random_state = 42)

In [28]:
x ,y

(array([[-0.49693203, -0.33912228,  0.22914552, ..., -1.17927302,
          0.45780561,  0.35600629],
        [ 0.01249932,  1.00744397,  0.14009566, ..., -1.76385344,
          0.93791554,  0.45936344],
        [-0.72021202, -1.24448645, -0.47229097, ...,  0.41394755,
         -0.5387903 , -0.26636053],
        ...,
        [ 1.01027459, -0.13092581,  1.18030384, ..., -1.98959095,
         -0.80579965,  0.88702644],
        [-1.20775939, -0.3807634 ,  0.12906749, ..., -0.77725344,
          0.59910333,  0.22671772],
        [ 1.14356604, -0.42459817, -0.31394763, ...,  1.24769039,
         -0.30704834, -0.40246308]]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
   

In [30]:
clf = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
clf.fit(x_train , y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [32]:
clf.score(x_test , y_test)

0.9133333333333333

In [56]:
kf = KFold(n_splits = 5 , random_state = 42 , shuffle=True)
kf_score = cross_val_score(clf , x , y , cv = kf)
kf_score

array([0.915, 0.925, 0.91 , 0.9  , 0.885])

In [58]:
kf_score.mean()

0.907

In [52]:
skf = StratifiedKFold(n_splits=5, random_state=42, shuffle=True)
skf_score = cross_val_score(clf, x, y, cv=skf)
skf_score

array([0.945, 0.92 , 0.89 , 0.885, 0.9  ])

In [54]:
skf_score.mean()

0.908